QR-Code: QRCodeStructToRaw.c File Reference
QRCodeStructToRaw.c File Reference
#include "../QRCode/model.h"
#include "../binaryConverter/binaryConverter.h"
#include "./QRCodeStructToRaw.h"
#include "../reedSolomon/reedSolomon.h"
#include <stdio.h>
#include <stdlib.h>
Functions
static int getIndexInMapCharacters (char query)
Returns index of searched char in mapCharacters.
static int isInMapCharacters (char query)
Searches for character in alphanumeric characters.
static int integrityCheckDataArray (struct QRCode data)
Checks if Array has only character present in alphanumericalCharacters.
static void addErrorCorrectionBlocks ()
Adds Error Correction blocks from Reed solomon code to QRCodeRawData.
void convertQrStructToRaw (struct QRCode data)
Converts struct with data to array with raw data.
Variables
const char mapAlphanumericalCharacters [45]
Map characters to special numbers(not ascii! alphanumerical code)
Function Documentation
addErrorCorrectionBlocks()
static void addErrorCorrectionBlocks () static
Adds Error Correction blocks from Reed solomon code to QRCodeRawData.
Stores correction blocks returned by createReedSolomon
Definition at line 57 of file QRCodeStructToRaw.c.
{
     // Convert Blocks into decimal data
     // 9 For the data and then 17 for the correction blocks
     int decimalNumbers[9 + 17];
     for (int i = 0; i < lengthRawData; i += 8){
         int tmp[8];
         for (int b = 0; b < 8; b++){
             tmp[b] = QRCodeRawData[i + b];
         }
         decimalNumbers[i / 8] = binToDec(tmp, 8);
     }
     int *decimalCorrectionBlocks = malloc(sizeof(int) * 17);
     // ECC Blocks is 17
     // Call reed Solomon wrapper function, returns 17 error codes
     decimalCorrectionBlocks = createReedSolomon(decimalNumbers);
     // Add correction Blocks to decimal Numbers
     for (int i = 0; i < 17; i++){
         decimalNumbers[9 + i] = decimalCorrectionBlocks[i];
     }
     // Convert Decimal Numbers with correction back to binary
     int counter = 0;
     for (int i = 0; i < 26; i++){
         struct BinaryNumber number = decToBin(decimalNumbers[i], 8);
         for (int a = 0; a < 8; a++){
             QRCodeRawData[counter] = number.array[a];
             counter++;
         }
     }
     // Adjust Lenght variable to new length
     lengthRawData = 26 * 8;
 }
References BinaryNumber::array, binToDec(), createReedSolomon(), decToBin(), lengthRawData, and QRCodeRawData.
convertQrStructToRaw()
void convertQrStructToRaw (struct QRCode data)
Converts struct with data to array with raw data.
Adds correction codes to data
Parameters
[in] data QRCode struct that holds information about qr-code about to be created
[out] QRCodeRawData array with binary data for QRCode
[out] lengthRawData integer that stores length of array
Returns
void
Definition at line 99 of file QRCodeStructToRaw.c.
{
     // Character Data of QRCode in binary (without id and length)
     int dataBlocksBinary[256];
     int lengthDataBlocksBinary = 0;
     integrityCheckDataArray(data);
     // Create copy of lengthOfData because that counts +1 if amount of chars in odd
     int lengthCache = data.lengthOfData;
     // Adjust length when using strings with odd length
     if(lengthCache % 2 == 1){
         lengthCache++;
     }
     // Create Blocks of 2 Characters and calculate binary Number
     for (int i = 0; i < lengthCache; i += 2){
         // Calculate Block Value
         int blockDecValue = getIndexInMapCharacters((char)data.data[i]) * 45;
         blockDecValue += (getIndexInMapCharacters((char)data.data[i + 1]) == -1 ? 0 : getIndexInMapCharacters((char)data.data[i + 1]));
         // Convert block value to binary number
         struct BinaryNumber tempBinNumber = decToBin(blockDecValue, 11);
         // Extend binary number into length of 11 Bits (attach 0)
         int missingZeroes = 11 - tempBinNumber.length;
         for (int a = lengthDataBlocksBinary; a < (lengthDataBlocksBinary + missingZeroes); a++){
             dataBlocksBinary[a] = 0;
         }
         int b = 0;
         for (int a = lengthDataBlocksBinary + missingZeroes; a < lengthDataBlocksBinary + 11; a++){
             dataBlocksBinary[a] = tempBinNumber.array[b];
             b++;
         }
         lengthDataBlocksBinary += 11;
     }
     // Write Type of Data (codification id)
     for (int i = 0; i < 4; i++){
         QRCodeRawData[i] = data.modeIndicator[i];
     }
     lengthRawData += 4;
     // Write length of data
     struct BinaryNumber tmpBinNumber = decToBin(data.lengthOfData, 9);
     for (int i = 0; i < 9; i++){
         QRCodeRawData[i + lengthRawData] = tmpBinNumber.array[i];
     }
     lengthRawData += 9;
     // Write processed payload to raw array
     for (int i = 0; i < (lengthCache / 2) * 11; i++){
         QRCodeRawData[i + lengthRawData] = dataBlocksBinary[i];
     }
     lengthRawData += (lengthCache / 2) * 11;
     // Add terminator (4 zeroes)
     for (int i = 0; i < 4; i++){
         QRCodeRawData[lengthRawData + i] = 0;
     }
     lengthRawData += 4;
     // Create blocks of eight out of QRCodeRawData
     // If zeroes are to add
     while (lengthRawData % 8 != 0){
         QRCodeRawData[lengthRawData + 1] = 0;
         lengthRawData++;
     }
     // We use the small version 1 Qr-Code so max bits are 72
     int specialBlock1[] = {1, 1, 1, 0, 1, 1, 0, 0};
     int specialBlock2[] = {0, 0, 0, 1, 0, 0, 0, 1};
     int counter = 0;
     // Fill up raw data with special blocks until max bits reached
     while (lengthRawData < 72){
         if (counter % 2 == 0){
             for (int i = 0; i < 8; i++){
                 QRCodeRawData[lengthRawData + i] = specialBlock1[i];
             }
         }else{
             for (int i = 0; i < 8; i++){
                 QRCodeRawData[lengthRawData + i] = specialBlock2[i];
             }
         }
         counter++;
         lengthRawData += 8;
     }
     addErrorCorrectionBlocks();
 }
References addErrorCorrectionBlocks(), BinaryNumber::array, QRCode::data, decToBin(), getIndexInMapCharacters(), integrityCheckDataArray(), BinaryNumber::length, QRCode::lengthOfData, lengthRawData, QRCode::modeIndicator, and QRCodeRawData.
getIndexInMapCharacters()
static int getIndexInMapCharacters (char query) static
Returns index of searched char in mapCharacters.
Definition at line 14 of file QRCodeStructToRaw.c.
{
     for (int i = 0; i < 45; i++){
         if (mapAlphanumericalCharacters[i] == query){
             return i;
         }
     }
     return -1;
 }
References mapAlphanumericalCharacters.
integrityCheckDataArray()
static int integrityCheckDataArray (struct QRCode data) static
Checks if Array has only character present in alphanumericalCharacters.
Parameters
[in] data QrStruct data to check integrity
Returns
status returns 0 if data is correct, -1 if not
Definition at line 43 of file QRCodeStructToRaw.c.
{
     for (int i = 0; i < data.lengthOfData; i++){
         if (isInMapCharacters(data.data[i]) == -1){
             fprintf(stderr, "Input data is not valid!\n");
             return -1;
         }
     }
     return 0;
 }
References QRCode::data, isInMapCharacters(), and QRCode::lengthOfData.
isInMapCharacters()
static int isInMapCharacters (char query) static
Searches for character in alphanumeric characters.
Parameters
[in] query Char query to search in alphanumericalCharacter
Returns
status returns 0 if char has been found -1 if not
Definition at line 28 of file QRCodeStructToRaw.c.
{
     for (int i = 0; i < 45; i++){
         if (query == mapAlphanumericalCharacters[i]){
             return 0;
         }
     }
     return -1;
 }
References mapAlphanumericalCharacters.
Variable Documentation
mapAlphanumericalCharacters
const char mapAlphanumericalCharacters[45]
Initial value:
= {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
                                              'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', '$', '%', '*', '+', '-', '.', '/', ':'}
Map characters to special numbers(not ascii! alphanumerical code)
Definition at line 8 of file QRCodeStructToRaw.c.