Write-QR-Code: QRCodeStructToRaw.h File Reference
QRCodeStructToRaw.h File Reference
Functions
void convertQrStructToRaw (struct QRCode data)
Converts struct with data to array with raw data.
Variables
int QRCodeRawData []
Processed Raw data.
int lengthRawData
Length of Raw data.
const char mapAlphanumericalCharacters [45]
Map characters to special numbers(not ascii! alphanumerical code)
Function Documentation
convertQrStructToRaw()
void convertQrStructToRaw (struct QRCode data)
Converts struct with data to array with raw data.
Adds correction codes to data
Parameters
[in] data QRCode struct that holds information about qr-code about to be created
[out] QRCodeRawData array with binary data for QRCode
[out] lengthRawData integer that stores length of array
Returns
void
Converts struct with data to array with raw data.
Character Data of QRCode in binary (without id and length)
Create Blocks of 2 Characters and calculate binary Number
Calculate Block Value
Convert block value to binary number
Extend binary number into length of 11 Bits (attach 0)
Write Type of Data (codification id)
Write length of data
Write processed payload to raw array
Add terminator (4 zeroes)
Create blocks of eight out of QRCodeRawData If zeroes are to add
Convert Blocks into decimal data 9 For the data and then 17 for the correction blocks
Input decimalNumbers in this Website https://www.thonky.com/qr-code-tutorial/show-division-steps ECC Blocks is 17 Scroll down to result and copy in here
Add correction Blocks to decimal Numbers
COnvert Decimal Numbers with correction back to binary
Adjust Lenght variable to new length
Definition at line 35 of file QRCodeStructToRaw.c.
{
     int dataBlocksBinary[256];
     int lengthDataBlocksBinary = 0;
     for(int i = 0; i < data.lengthOfData; i++){
         if(isInMapCharacters(data.data[i]) == -1){
             fprintf(stderr, "Input data is not valid!\n");
             return;
         }
     }
     for(int i = 0; i < data.lengthOfData; i+=2){
         int blockDecValue = getIndexInMapCharacters((char)data.data[i]) * 45;
         blockDecValue += getIndexInMapCharacters((char)data.data[i+1]);
         struct BinaryNumber tempBinNumber = decToBin(blockDecValue, 11);
         int missingZeroes = 11 - tempBinNumber.length;
         for(int a = lengthDataBlocksBinary; a < (lengthDataBlocksBinary + missingZeroes); a++){
             dataBlocksBinary[a] = 0;
         }
         int b = 0;
         for(int a = lengthDataBlocksBinary + missingZeroes; a < lengthDataBlocksBinary + 11; a++){
             dataBlocksBinary[a] = tempBinNumber.array[b];
             b++;
         }
         lengthDataBlocksBinary += 11;
     }
     for(int i = 0; i < 4; i++){
         QRCodeRawData[i] = data.codificationId[i];
     }
     lengthRawData += 4;
     struct BinaryNumber tmpBinNumber = decToBin(data.lengthOfData, 9);
     for(int i = 0; i < 9; i++){
         QRCodeRawData[i+lengthRawData] = tmpBinNumber.array[i];
     }
     lengthRawData += 9;
     for(int i = 0; i < (data.lengthOfData/2)*11; i++){
         QRCodeRawData[i+lengthRawData] = dataBlocksBinary[i];
     }
     lengthRawData += (data.lengthOfData/2)*11;
     for(int i = 0; i < 4; i++){
         QRCodeRawData[lengthRawData + i] = 0;
     }
     lengthRawData += 4;
     while(lengthRawData % 8 != 0){
         QRCodeRawData[lengthRawData + 1] = 0;
         lengthRawData++;
     }
     // We use the small version 1 Qr-Code so max bits are 72
     int specialBlock1[] = {1, 1, 1, 0, 1, 1, 0, 0};
     int specialBlock2[] = {0, 0, 0, 1, 0, 0, 0 ,1};
     int counter = 0;
     // Fill up raw data with special blocks until max bits reached
     while(lengthRawData < 72){
         if(counter % 2 == 0){
             for(int i = 0; i < 8; i++){
                 QRCodeRawData[lengthRawData + i] = specialBlock1[i];
             }
         }else{
             for(int i = 0; i < 8; i++){
                 QRCodeRawData[lengthRawData + i] = specialBlock2[i];
             }
         }
         counter++;
         lengthRawData += 8;
     }
     int decimalNumbers[9+17];
     for(int i = 0; i < lengthRawData; i+=8){
         int tmp[8];
         for(int b = 0; b < 8; b++){
             tmp[b] = QRCodeRawData[i+b];
         }
         decimalNumbers[i/8] = binToDec(tmp, 8);
     }
     printf("Decimal Data: ");
     for(int i = 0; i < 9; i++){
         printf("%d, ", decimalNumbers[i]);
     }
     printf("\n");
     createReedSolomon(decimalNumbers);
     int decimalCorrectionBlocks[] = {208, 147, 120, 235, 20, 36, 10, 42, 73, 162, 140, 142, 217, 162, 207, 0, 62};
     for(int i = 0; i < 17; i++){
         decimalNumbers[9+i] = decimalCorrectionBlocks[i];
     }
     counter = 0;
     for(int i = 0; i < 26; i++){
         struct BinaryNumber number = decToBin(decimalNumbers[i], 8);
         for(int a = 0; a < 8; a++){
             QRCodeRawData[counter] = number.array[a];
             counter++;
         }
     }
     lengthRawData = 26*8;
     printf("Binary Data: ");
     for(int i = 0; i < lengthRawData; i++){
         printf("%d", QRCodeRawData[i]);
     }
     printf("\n");
 }
References BinaryNumber::array, binToDec(), QRCode::codificationId, createReedSolomon(), QRCode::data, decToBin(), getIndexInMapCharacters(), isInMapCharacters(), BinaryNumber::length, QRCode::lengthOfData, lengthRawData, and QRCodeRawData.
Variable Documentation
lengthRawData
int lengthRawData
Length of Raw data.
Definition at line 8 of file QRCodeStructToRaw.h.
mapAlphanumericalCharacters
const char mapAlphanumericalCharacters[45]
Map characters to special numbers(not ascii! alphanumerical code)
Definition at line 11 of file QRCodeStructToRaw.h.
QRCodeRawData
int QRCodeRawData[]
Processed Raw data.
Definition at line 6 of file QRCodeStructToRaw.h.