QR-Code: createPBMImage.c File Reference
createPBMImage.c File Reference
#include "createPBMImage.h"
#include <string.h>
#include <stdio.h>
Data Structures
struct PBMImageMetadata
Struct holds image metadata.
Functions
static int initialeFileHandler ()
Opens file handler stored in a global pointer.
static void closeFileHandler ()
Closes file handler.
static void writeMetadata ()
Writes Metadata to bitmap image.
static void writeArray (int rectangle[21][21])
Writes 2d Array in .pbm file.
int createPBMImage (int rectangle[21][21])
Wrapper function, creates .pbm image from 2d array with data.
Variables
struct PBMImageMetadata image
Create Image struct.
FILE * fileptr
File pointer to output file.
Function Documentation
closeFileHandler()
static void closeFileHandler () static
Closes file handler.
Definition at line 38 of file createPBMImage.c.
{
     fclose(fileptr);
 }
References fileptr.
createPBMImage()
int createPBMImage (int rectangle[21][21])
Wrapper function, creates .pbm image from 2d array with data.
Parameters
[in] rectangle[][] 2d array with data to write
Returns
status Returns status (-1)=something is wrong
Definition at line 64 of file createPBMImage.c.
{
     // Fill image metadata
     strncpy(image.magicNumber, "P1", 2);
     image.height = 21;
     image.width = 21;
     // Create File handler, return -1 if something is wrong
     if(initialeFileHandler() == -1){
         perror("File could not be opened!\n");
         return -1;
     }
     // Write metadata to file
     writeMetadata();
     // Writes array rectangle to file
     writeArray(rectangle);
     // Closes File Handler
     closeFileHandler();
 }
References closeFileHandler(), PBMImageMetadata::height, image, initialeFileHandler(), PBMImageMetadata::magicNumber, rectangle, PBMImageMetadata::width, writeArray(), and writeMetadata().
initialeFileHandler()
static int initialeFileHandler () static
Opens file handler stored in a global pointer.
Definition at line 28 of file createPBMImage.c.
{
     fileptr = fopen("output.pbm", "w");
     if(fileptr == NULL){
         return -1;
     }
 }
References fileptr.
writeArray()
static void writeArray (int rectangle[21][21]) static
Writes 2d Array in .pbm file.
Definition at line 54 of file createPBMImage.c.
{
     for (int i = 0; i < 21; i++){
         for(int j = 0; j < 21; j++){
             fprintf(fileptr, "%d ", rectangle[i][j]);
         }
         fprintf(fileptr, "\n");
     }
 }
References fileptr, and rectangle.
writeMetadata()
static void writeMetadata () static
Writes Metadata to bitmap image.
Metadata consists of magic number and size
Definition at line 46 of file createPBMImage.c.
{
     fprintf(fileptr, "%s\n", image.magicNumber);
     fprintf(fileptr, "%d %d\n", image.height, image.width);
 }
References fileptr, PBMImageMetadata::height, image, PBMImageMetadata::magicNumber, and PBMImageMetadata::width.
Variable Documentation
fileptr
FILE* fileptr
File pointer to output file.
Definition at line 22 of file createPBMImage.c.
image
struct PBMImageMetadata image
Create Image struct.
Definition at line 1 of file createPBMImage.c.