Write-QR-Code: createPBMImage.h File Reference
createPBMImage.h File Reference
Functions
void createPBMImage (int rectangle[21][21])
Function Documentation
createPBMImage()
void createPBMImage (int rectangle[21][21])
Definition at line 50 of file createPBMImage.c.
{
     // Fill image metadata
     strncpy(image.magicNumber, "P1", 2);
     image.height = 21;
     image.width = 21;
     if(initialeFileHandler() == -1){
         perror("File could not be opened!\n");
         return -1;
     }
     writeMetadata();
     writeArray(rectangle);
     closeFileHandler();
 }
References closeFileHandler(), PBMImageMetadata::height, image, initialeFileHandler(), PBMImageMetadata::magicNumber, rectangle, PBMImageMetadata::width, writeArray(), and writeMetadata().