name: C/C++ CI

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make-test
      run: make test
    - name: clean
      run: make clean
    - name: doxygen-docs
      run: sudo apt install doxygen
      run: doxygen docs/doxygen
